steps:
  # 1. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_TAG}", "./backend"]

  # 2. Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_TAG}"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run services update backend \
          --image "${_IMAGE_TAG}" \
          --region "${_REGION}" \
          --service-account "${_SERVICE_ACCOUNT}" \
          --memory=512Mi \
          --cpu=1 \
          --timeout=300 \
          --no-allow-unauthenticated \
          --add-cloudsql-instances "${_CLOUD_SQL_CONNECTION_NAME}" \
          --set-env-vars "FLASK_ENV=production,DB_HOST=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME},DB_PORT=5432,DB_USER=${_DB_USER},DB_NAME=${_DB_NAME}" \
          --update-secrets "DB_PASSWORD=db-password:latest,SECRET_KEY=flask-key:latest,JWT_SECRET_KEY=jwt-key:latest"  # 4. (Re)create and run migration job
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        gcloud run jobs delete backend-migrate --region "${_REGION}" --quiet || true
        gcloud run jobs create backend-migrate \
          --image "${_IMAGE_TAG}" \
          --region "${_REGION}" \
          --service-account "${_SERVICE_ACCOUNT}" \
          --set-cloudsql-instances "${_CLOUD_SQL_CONNECTION_NAME}" \
          --set-env-vars "FLASK_ENV=production,FLASK_APP=wsgi:app,DB_HOST=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME},DB_PORT=5432,DB_USER=${_DB_USER},DB_NAME=${_DB_NAME}" \
          --update-secrets "DB_PASSWORD=db-password:latest,SECRET_KEY=flask-key:latest,JWT_SECRET_KEY=jwt-key:latest" \
          --command "flask" --args "db","upgrade" \
          --task-timeout 10m
        gcloud run jobs execute backend-migrate --region "${_REGION}" --wait

  # 5. (Re)create and run seed job
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        gcloud run jobs delete backend-seed --region "${_REGION}" --quiet || true
        gcloud run jobs create backend-seed \
          --image "${_IMAGE_TAG}" \
          --region "${_REGION}" \
          --service-account "${_SERVICE_ACCOUNT}" \
          --set-cloudsql-instances "${_CLOUD_SQL_CONNECTION_NAME}" \
          --set-env-vars "FLASK_ENV=production,FLASK_APP=wsgi:app,DB_HOST=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME},DB_PORT=5432,DB_USER=${_DB_USER},DB_NAME=${_DB_NAME}" \
          --update-secrets "DB_PASSWORD=db-password:latest,SECRET_KEY=flask-key:latest,JWT_SECRET_KEY=jwt-key:latest" \
          --command "flask" --args "seed" \
          --task-timeout 10m
        gcloud run jobs execute backend-seed --region "${_REGION}" --wait

substitutions:
  _PROJECT_ID: "project-5291a779-124c-4d04-8a5"
  _REGION: "europe-west1"
  _IMAGE_TAG: "europe-west1-docker.pkg.dev/project-5291a779-124c-4d04-8a5/cloud-run-source-deploy/habcube-backend:latest"
  _SERVICE_ACCOUNT: "1089871134307-compute@developer.gserviceaccount.com"
  _CLOUD_SQL_CONNECTION_NAME: "project-5291a779-124c-4d04-8a5:europe-west1:habcube"
  _DB_USER: "postgres"
  _DB_NAME: "postgres"

options:
  logging: CLOUD_LOGGING_ONLY
