"""Add habits tables

Revision ID: 29b716086a11
Revises:
Create Date: 2025-10-15 15:53:15.057916

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "29b716086a11"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "habits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deadline_time", sa.Time(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum("daily", "weekly", "custom", name="frequency_enum"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("color", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habit_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("total_completions", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=False),
        sa.Column("last_completed", sa.Date(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habit_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completion_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habit_tasks")
    op.drop_table("habit_statistics")
    op.drop_table("habits")
    # ### end Alembic commands ###
