"""add_type_to_habits

Revision ID: b73f01ec3653
Revises: 7b3ce3e44354
Create Date: 2025-11-20 10:09:42.053629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b73f01ec3653'
down_revision = '7b3ce3e44354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('WATER', 'CODE', 'SPORT', 'LANGUAGE', 'READ', name='habittype', native_enum=False), nullable=True))
        batch_op.alter_column('frequency',
               existing_type=postgresql.ENUM('EVERY_30_MIN', 'HOURLY', 'EVERY_3_HOURS', 'EVERY_6_HOURS', 'DAILY', 'WEEKLY', 'MONTHLY', name='frequency_enum'),
               type_=sa.Enum('EVERY_30_MIN', 'HOURLY', 'EVERY_3_HOURS', 'EVERY_6_HOURS', 'DAILY', 'WEEKLY', 'MONTHLY', name='frequencytype', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('WATER', 'FITNESS', 'BOOK', 'BED', 'RESTAURANT', 'LEAF', 'MEDICAL', 'WALK', 'BICYCLE', 'PIZZA', 'MOON', 'SUNNY', 'HEART', 'FLAME', 'MUSICAL_NOTES', 'BARBELL', 'CAFE', 'BRUSH', 'CODE', 'GAME_CONTROLLER', 'CAMERA', 'FOOTBALL', 'LANGUAGE', 'PENCIL', 'SCHOOL', 'TIMER', 'PHONE_PORTRAIT', 'MAIL', 'CHATBUBBLES', 'CAR', 'TRAIN', 'AIRPLANE', 'HOME', 'BUSINESS', 'WALLET', 'CART', 'GIFT', 'FLOWER', 'SNOW', 'STAR', 'TROPHY', 'RIBBON', 'SPARKLES', 'ROCKET', 'BULB', 'MEGAPHONE', 'HOURGLASS', 'CALENDAR', 'ALARM', 'EYE', 'GLASSES', 'HEADSET', 'MAP', 'LOGO_TIKTOK', 'LOGO_INSTAGRAM', name='habiticon', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'star'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Enum('WATER', 'FITNESS', 'BOOK', 'BED', 'RESTAURANT', 'LEAF', 'MEDICAL', 'WALK', 'BICYCLE', 'PIZZA', 'MOON', 'SUNNY', 'HEART', 'FLAME', 'MUSICAL_NOTES', 'BARBELL', 'CAFE', 'BRUSH', 'CODE', 'GAME_CONTROLLER', 'CAMERA', 'FOOTBALL', 'LANGUAGE', 'PENCIL', 'SCHOOL', 'TIMER', 'PHONE_PORTRAIT', 'MAIL', 'CHATBUBBLES', 'CAR', 'TRAIN', 'AIRPLANE', 'HOME', 'BUSINESS', 'WALLET', 'CART', 'GIFT', 'FLOWER', 'SNOW', 'STAR', 'TROPHY', 'RIBBON', 'SPARKLES', 'ROCKET', 'BULB', 'MEGAPHONE', 'HOURGLASS', 'CALENDAR', 'ALARM', 'EYE', 'GLASSES', 'HEADSET', 'MAP', 'LOGO_TIKTOK', 'LOGO_INSTAGRAM', name='habiticon', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'star'::character varying"))
        batch_op.alter_column('frequency',
               existing_type=sa.Enum('EVERY_30_MIN', 'HOURLY', 'EVERY_3_HOURS', 'EVERY_6_HOURS', 'DAILY', 'WEEKLY', 'MONTHLY', name='frequencytype', native_enum=False),
               type_=postgresql.ENUM('EVERY_30_MIN', 'HOURLY', 'EVERY_3_HOURS', 'EVERY_6_HOURS', 'DAILY', 'WEEKLY', 'MONTHLY', name='frequency_enum'),
               existing_nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
